### ISSUE TITLE
Nested check info?

### ISSUE THREAD

**Issue by jackfirth** [racket/rackunit#10]
Suppose I have a situation where I want to register a logically related group of check infos. Currently there are two ways to do this:
1. Group them into a hash and register a single check info with the name describing what the group is

``` racket
--------------------
FAILURE
name:             some-check
location:         (unsaved-editor 12 0 126 5)
expression:       (foo)
params:           ()
some-extra-info:  #hash((a . 1) (b . 2))
--------------------
```
1. Register them all at the top level

``` racket
--------------------
FAILURE
name:       some-check
location:   (unsaved-editor 12 0 126 5)
expression: (foo)
params:     ()
a:          1
b:          2
--------------------
```

1) is undesirable to me because it's difficult to read, especially if there's more than two or three keys. 2) is undesirable to me because now I've lost the information that these are logically grouped keys, and I can't name them by group.

Ideally I would like some way to have a check failure say this:

``` racket
--------------------
FAILURE
name:             some-check
location:         (unsaved-editor 12 0 126 5)
expression:       (foo)
params:           ()
some-extra-info:
  a:              1
  b:              2
--------------------
```

Would this be useful to others? Is there a better way I should attempt to do this?

**Comment by jeapostrophe** [comment]
Go for it! I suggest that you have the single some-extra-info field but it's value is a (make-rackunit-table X) where X is the hash, then during formatting it looks for this structure and prints it nice.
