### ISSUE TITLE
Command line output includes noise

### ISSUE THREAD

**Issue by jackfirth** [racket/rackunit#11]
When run in DrRacket, a failing test includes clickable error buttons pointing to the source location of the failing test and showing the stacktrace of the error, in addition to a "Check failure" message for the error. When run at the command line, this output is given:

```
--------------------
FAILURE
name:       check
location:   some-location-data
expression: (check string=? "foo" "bar")
params:     (#<procedure:string=?> "foo" "bar")

Check failure
--------------------
```

The extra whitespace line and "Check failure" message seems unnecessary. Some custom checks customize the error message, but the built in checks don't. Would it be better to either have the default checks include human-readable messages with more information, to not print those two lines at the command line at all, or to remain as they are now?

**Comment by jeapostrophe** [comment]
I think you should balete those two useless lines. We know it is a failure from before, so blast it away.
