### ISSUE TITLE
Is there a way to have rackunit render picts inside the "check-info stack"?

### ISSUE THREAD

**Issue by aymanosman** [racket/rackunit#130]
![Screen Shot 2020-12-26 at 23 13 00](https://user-images.githubusercontent.com/3605049/103172979-99824600-484f-11eb-9a2a-229837d3b6fd.png)

## Problem
The "check-info stack" facility is unable to display visual data.

## Motivation

While working on a graph algorithm, I found myself wanting to visualize the graphs I was computing. `rackunit` makes it convenient to associate extra information with a test case failure through the "check-info stack". I've always used that facility to associate textual data with my test cases, but now I found myself wanting to add visual data to that.

## Workaround

Since I can only display text in test failures, I simply included the dot representation of the graph, like so:

![Screen Shot 2020-12-27 at 14 31 33](https://user-images.githubusercontent.com/3605049/103173615-00a1f980-4854-11eb-8eec-02daa1817f53.png)

**Comment by rfindler** [comment]
It looks like rackunit is explicitly turning values into strings via `info-value->string` which isn't compatible with actually seeing certain values. For example, in this code, the first line prints "#(struct:object...." while the second shows the image.

```
#lang racket
(require 2htdp/image)
(displayln (~a (circle 50 "solid" "blue")))
(displayln (circle 50 "solid" "blue"))
```

picts need a bit more help; they have to be `print`ed to show up. In this code, the first two show "#<pict>" and the last two show the picts themselves.

```
#lang racket
(require pict)
(write (circle 50))
(display (format "~a" (circle 50)))
(print (circle 50))
(printf "~v" (circle 50))
```

It would be good if rackunit would print the values so that they'd show up in uses like this one, at least.

```
#lang racket
(require pict rackunit)
(check-equal? (circle 50) (circle 40))
```

which currently prints as:

```
Welcome to DrRacket, version 7.9.0.17--2020-12-24(dd1061f0/d) [cs].
Language: racket, with debugging; memory limit: 128 MB.
--------------------
. FAILURE
name:       check-equal?
location:   unsaved-editor:3:0
actual:     #<pict>
expected:   #<pict>
--------------------
```

**Comment by aymanosman** [comment]
Thanks for the pointers @rfindler.

It looks like it wouldn't be too difficult to support this use case. Here are the results of some quick hacking:

![Screen Shot 2020-12-27 at 18 44 37](https://user-images.githubusercontent.com/3605049/103177592-c7798180-4873-11eb-81b6-5665f4ca6b90.png)

All I did was change the [check-info-stack->string](https://github.com/racket/rackunit/blob/856ab043bf7e25dd904d6eaccdd3a560c89b018a/rackunit-lib/rackunit/private/format.rkt#L56) function to `print-check-info-stack` and propogate those changes all the way.

It looks promising, if you'd be interested in a patch.
