### ISSUE TITLE
check-exn does not accept regexp

### ISSUE THREAD

**Issue by djtango** [racket/rackunit#18]
Racket version 6.4
The docs suggest that check-exn can accept a regexp, but the following fails (please let me know if I can provide additional details):

```
-> (run-tests (test-suite "" (check-exn (regexp-quote "huh?") (thunk (error "huh?")))))
--------------------
 > #f
Unnamed test 
ERROR
name:       check-exn
location:   readline-input:10:26
params:     "huh\\?"
#<procedure:temp6>
; check-exn: contract violation
;   expected: (-> any/c any/c)
;   given: "huh\\?"
; [,bt for context]

```

```
-> (run-tests (test-suite "" (check-exn #rx#"huh?" (thunk (error "huh?")))))
--------------------
 > #f
Unnamed test 
ERROR
name:       check-exn
location:   readline-input:12:26
params:     #rx#"huh?"
#<procedure:temp14>
; check-exn: contract violation
;   expected: (-> any/c any/c)
;   given: #rx#"huh?"
; [,bt for context]
```

**Comment by rmculpepper** [comment]
The first fails because `regexp-quote` returns a string, not a regexp. Try converting the result to a regexp:

    (check-exn (regexp (regexp-quote "huh?")) (thunk (error "huh?")))

The second fails because the `#rx#"..."` reader syntax constructs a "bytes-regexp", not an ordinary string regexp. Try removing the second `#`:

    (check-exn #rx"huh?" (thunk (error "huh?")))

**Comment by djtango** [comment]
Aha! That worked, thank you very much for the fast reply - sorry for the false alarm, I was thrown off by the `;   expected: (-> any/c any/c)` not matching the `(orc (-> any/c any/c) regexp?)` contract in the docs.

**Comment by rmculpepper** [comment]
Good point. I just committed a fix to the error message.
