### ISSUE TITLE
Question: How can I print assertions?

### ISSUE THREAD

**Issue by dey-dey** [racket/rackunit#4]
I've become quite fond of the TAP protocol over time, and I understand that it would be somewhat trivial to implement that on top of rackunit but I was wondering, is there a way to print assertions out of the box? I tried `(run-tests tests 'verbose)` but it seems to only print failures?

Any info is much appreciated!

**Comment by daedelus-j** [comment]
for good measure TAP spec: https://testanything.org/tap-specification.html

**Comment by jackfirth** [comment]
`run-tests` won't print anything for passing tests by design. You could use `fold-test-results` to make your own test runner that prints output satisfying the TAP protocol.
