### ISSUE TITLE
Travis build errors when running installer for current snapshot

### ISSUE THREAD

**Issue by jackfirth** [racket/rackunit#68]
[Logs](https://travis-ci.org/racket/rackunit/builds/262375797?utm_source=email&utm_medium=notification). Seems to be due to some change in the installer script, it's raising syntax errors now.

**Comment by bennn** [comment]
The installer script is a 404 for me right now.
https://plt.eecs.northwestern.edu/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh

Maybe the server went down during the download, so the Travis build got an incomplete script?

**Comment by florence** [comment]
Yes, the build script got interrupted partway through, so that the linux build 404'd. That link should be fixed now! I've restarted the build and it seems to have progressed past that point.

**Comment by rfindler** [comment]
Just to be clear, the northwestern snapshot build machine seems to have gotten sick. We're nursing it back to health, but there have not been any recent builds and it needs a lot of TLC.
