### ISSUE TITLE
message argument to check-exn is not useful anymore

### ISSUE THREAD

**Issue by rfindler** [racket/rackunit#69]
In version 6.9, the code below prints out a line that includes "my message" (which is good, in my opinion). In 6.10, it also prints out "my message" (which is good), but also includes what appears to be the default value of the message field "Wrong exception raised" (I have no opinion about the inclusion of that line). The current version (as of commit 5ffb7ce05a), includes only the "Wrong exception raised" line (which seems bad to me).

```
#lang racket
(require rackunit)

(check-exn
 #rx"two"
 (λ () (error 'f "one"))
 "my message")
```

**Comment by bennn** [comment]
There's a pull request for this: #65

**Comment by rfindler** [comment]
Ah, sorry about that.
