### ISSUE TITLE
Publicize `location.rkt`

### ISSUE THREAD

**Issue by bennn** [racket/rackunit#7]
I've been [using](https://github.com/bennn/rackunit-abbrevs/blob/master/private/rackunit-abbrevs.rkt#L27) a copy of `syntax->location` to write new test forms, and it looks like @schuster [has too](https://github.com/schuster/asyncunit/blob/master/main.rkt#L55).

Can we make that function public? If not, can we add a `location` or `srcloc` argument to `define-check`?

**Comment by schuster** [comment]
+1 to making `syntax->location` public (especially somewhere more central to syntax objects, rather than the `rackunit` library). 

Adding a `location` argument to `define-check` sounds useful, too. It would let me actually use `define-check` in some cases instead of writing my checks manually with syntax extensions.

**Comment by stamourv** [comment]
I agree with the general idea, but I don't know whether `syntax->location` is exactly what we want.
Various parts of Racket alternatively use lists, vectors or `srcloc` structs for source locations. Some APIs accept one, others one of the others. Others still use syntax objects as proxies for location. It's kind of a mess.

I think we should pick one and stick with it. I'd like to fix that, but there are other things higher on the list. In the meantime, I'm a bit hesitant to pile on more functions that contribute to the problem.

**Comment by rfindler** [comment]
FWIW, I think the srcloc struct is the best one. And probably most of what
we need is steering in the docs (as the places that accept other things are
for backwards compatibility).

Even better if the srcloc struct were prefab, tho....

Robby

**Comment by bennn** [comment]
Cool, I pushed my current thoughts as #8. I'm really not happy adding more cases to the syntax-case, so I'll marinate on this a little longer.

**Comment by bennn** [comment]
Closing because [`syntax/srcloc`](http://docs.racket-lang.org/syntax/Source_Locations.html) and [`with-check-info*`](http://docs.racket-lang.org/rackunit/api.html#%28def._%28%28lib._rackunit%2Fmain..rkt%29._with-check-info%2A%29%29) solve this problem for me.

Here's an example `check-true*` macro that expands to a sequence of `check-true`. The checks produced by expansion have "the right" locations:

```
#lang racket/base
(module+ test
  (require rackunit
           (for-syntax syntax/srcloc racket/base syntax/parse))

  (define-syntax (check-true* stx)
    (syntax-parse stx
     [(_ thing* ...)
      ;#:with (srcloc* ...) (map build-source-location-list (syntax-e #'(thing* ...)))
      #`(begin
          #,@(for/list ([thing (in-list (syntax-e #'(thing* ...)))])
               #`(with-check-info* (list (make-check-location '#,(build-source-location-list thing)))
                   (λ () (check-true #,thing)))))]))

  (check-true*
    (and #true #true)
    (and #false #true)
    3))
```

Running `raco test file.rkt` gives:
```
raco test: (submod "file.rkt" test)
--------------------
FAILURE
name:       check-true
location:   file.rkt:17:4
params:     (#f)
expression: (check-true (and #f #t))
--------------------
--------------------
FAILURE
name:       check-true
location:   file.rkt:18:4
params:     (3)
expression: (check-true 3)
--------------------
2/3 test failures
```
