### ISSUE TITLE
Improve handling of `test-log!` and `current-check-around`

### ISSUE THREAD

**Issue by jackfirth** [racket/rackunit#70]
Today, checks log failures / successes using `test-log!` in a context outside `current-check-around`. This means the following expression:

```racket
(parameterize ([current-check-around (lambda (thnk) (thnk))])
  (check-equal? 1 2))
```

... *appears* to evaluate `(check-equal? 1 2)` without printing anything and with a check failure exception raised. But it has the hidden side effect of logging a failure with `test-log!`. This causes confusion resulting in issues like #14, and makes it difficult to implement a fix to #9.

Instead, I propose the following changes:

1. Call `test-log!` as part of `current-check-around`
2. Make `test-case` and `test-suite` log results once-per-case-or-suite instead of once-per-check, since the entire case or suite is conceptually a single test. If this isn't done, `test-case` and `test-suite` would need to reproduce the current behavior which could be tricky.
3. Make `define-check` use a different version of `current-check-around` in the body of `define-check` so nested checks raise exceptions, deferring failure printing and test logging to the outermost check's current check handler. This ought to solve #9.

**Comment by jackfirth** [comment]
cc @zenspider

**Comment by jeapostrophe** [comment]
This makes sense to me

**Comment by zenspider** [comment]
Not sure I understand number 2, but yes please.
